baseURL = "https://hjlarry.github.io/"
languageCode = "zh-cn"
title = "Home"
theme = "hugo-book"
publishdir = "."
defaultContentLanguage = "cn"

# Book configuration
disablePathToLower = true
enableGitInfo = true

[languages]
[languages.cn]
  languageName = 'Chinese'
  contentDir = 'content'
  weight = 1

[params]
    BookToC = 3
    BookLogo = 'logo.png'
    BookRepo = 'https://github.com/hjlarry/hjlarry.github.io'
    BookSearch = true
    BookEditPath = 'edit/master/content'
    BookMenuBundle = '/menu'

# Social Links
	email = "ultrahe@gmail.com"
	github = "https://github.com/hjlarry/"
	twitter = "https://twitter.com/hjlarry"