# Project information
site_name: 非法操作的笔记
site_url: https://hjlarry.github.io/
site_author: 非法操作

# Repository
repo_name: hjlarry/hjlarry.github.io
repo_url: https://github.com/hjlarry/hjlarry.github.io

# Configuration
theme:
  name: material
  logo: assets/logo.png
  icon:
    repo: fontawesome/brands/github

 # Default values, taken from mkdocs_theme.yml
  language: zh
  features:
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: deep orange
      accent: white
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/logo.png

extra_css:
  - assets/extra.css
# Plugins
plugins:
  - search

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/hjlarry
    - icon: fontawesome/regular/envelope
      link: mailto:ultrahe@gmail.com
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/hjlarry
    - icon: fontawesome/brands/telegram
      link: https://t.me/hjlarry
    - icon: fontawesome/brands/paypal
      link: https://paypal.me/hjlarry

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.mark
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.tabbed:
      alternate_style: true

# Page tree
nav: 
 - 计算机基础: 
   - 硬件: sicp/hardware.md
   - 软件: sicp/software.md
   - 程序: sicp/program.md 
   - 汇编: sicp/asm.md 
 - GO语言: 
   - 字典: go/map.md
   - 闭包: go/closure.md
   - 延迟调用: go/defer.md
   - 并发调度: go/goroutine.md
   - 内存分配: go/alloc.md
   - 垃圾回收: go/gc.md
   - 锁: go/lock.md
 - Python语言: 
   - 内存管理: python/memory.md
   - 解释器: python/interpreter.md
   - 技巧工具: python/tools.md
 - MySQL: 
   - 查询: mysql/query.md
   - 原理: mysql/theory.md
 - 其他: 
   - git: other/git.md
   - docker: other/docker.md
   - raft: other/raft.md
   - shell: other/shell.md
   - security: other/security.md
   - 面向对象: other/oop.md
   - 网络协议: other/protocol.md
   - 系统工具: other/tools.md